### ISSUE TITLE
Doesn't work with FF 34.0.5

### ISSUE THREAD

**Issue by davidegiannella** [Thiht/markdown-viewer#36] opened 2015-01-13 14:04 UTC
After the update to FF 34.0.5 whenever I try to open a local `.md` file, it prompts me with what I want to open it (let's say emacs) rather than viewing it in the browser itself.

**Comment by cmtonkinson** [comment] 2015-03-27 12:13
Or `36.0.4`

**Comment by klonos** [comment] 2015-03-29 00:08
Just for the record, it works for me in fx 39.0a1 x64 latest builds. I guess you guys will have to wait until that version is released as stable :smile:

**Comment by Thiht** [comment] 2015-03-29 13:57
With the version 36 aurora, I had this problem with the built-in pdf.js didn't work for me (it prompted to download the pdf instead of reading it). Can you try to completely reinstall Firefox, including config files, preferences, etc. ? It worked for me with pdf.js

**Comment by fpirsch** [comment] 2015-03-29 15:39
Everything fine here with FF36 Ubuntu and Windows.

**Comment by MaerF0x0** [comment] 2015-04-13 22:46
No worky for 37.0.1 on OS X

**Comment by davidegiannella** [comment] 2015-04-15 10:04
Tried to start firefox, 37.0.1 this time, with a new profile having only MD viewer installed but still it doesn't work. Seems we'll have to wait for FF 39.

**Comment by hahcho** [comment] 2015-06-02 14:11
The same with `firefox 38.0-1` on `Arch`.

**Comment by dizzib** [comment] 2015-06-22 07:56
Same problem after upgrade FF from 38.0 to 38.0.5. Problem even persists after downgrade back to 38.0.

**Comment by klonos** [comment] 2015-06-22 14:16
Still works fine in 41 nightly builds. Must be some kind of regression in 38.

**Comment by fpirsch** [comment] 2015-06-22 17:36
This is NOT related to FF 38. It works fine here with 38 and 38.0.5 on both Ubuntu and Windows, I'm using it every day.
This problem must be somewhere else, e.g. in the OS config.

**Comment by RGBD** [comment] 2015-07-24 21:42
Do not work.
Firefox 39.0
Both Fedora 22 and Arch Linux.

**Comment by davidegiannella** [comment] 2015-08-04 09:29
what details can I provide for better investigate and reproduce this issue? FF 39.0 and still not working.

I played around though so maybe can be something else now.

**Comment by wangjiezhe** [comment] 2015-08-07 05:24
It doesn't work for me on `firefox 39.0-1` on `arch`.

**Comment by Thiht** [comment] 2015-08-07 10:03
Progress report: I was able to reproduce the "not working" bug on Fedora with FF39, so I guess there was a change in FF's API or something. I tried several minor modifications on my side but weren't able to make it work yet... So some investigations will be needed on what could be broken. As far as I can tell, it may require checking on FF's source code since the [doc on streamconverters](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIStreamConverter) is kinda sketchy. It could take a while before it works again.

Could some of you (with the bug) try these two add-ons and tell here if they work, so I can compare what differs with markdown viewer ?

* https://addons.mozilla.org/fr/firefox/addon/jsonview/
* https://addons.mozilla.org/fr/firefox/addon/open-in-browser/

**Comment by wangjiezhe** [comment] 2015-08-08 03:09
The first one work fine  for me,

![2015-08-08-110612_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5236768/9148815/b6e53948-3dbd-11e5-9d01-ab7d81dad023.png)


but the second doesn't with local files.

![2015-08-08-105202_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5236768/9148819/cb297b9e-3dbd-11e5-937c-02720e8e25b8.png)
![2015-08-08-105204_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5236768/9148820/d3591298-3dbd-11e5-9c06-149e6d8c0e44.png)

**Comment by raphael0202** [comment] 2015-09-21 11:11
It also doesn't work for me, I get a prompt asking where to save the file. On Fedora 22, Firefox 40.0.3

**Comment by RGBD** [comment] 2015-10-03 09:51
Not working. Firefox 41.0.1 x86_64 Arch Linux

**Comment by WnP** [comment] 2015-10-30 17:03
@Thiht both [jsonview](https://addons.mozilla.org/fr/firefox/addon/jsonview/) and [open-in-browser](https://addons.mozilla.org/fr/firefox/addon/open-in-browser/) works as expected here on firefox `40.0.3`, but markdown-viewer doesn't render mardown at all

**Comment by WnP** [comment] 2015-10-30 18:09
setting:
```xml
<RDF:Description RDF:about="urn:mimetype:text/plain"
        NC:value="text/plain"
        NC:fileExtensions="md"
        NC:description="Text Document">
    <NC:handlerProp RDF:resource="urn:mimetype:handler:text/plain"/>
</RDF:Description>
```
in `~/.mozilla/firefox/*default/mimeTypes.rdf` fix this issue for me

all credits are for [Ryan Chapin](  http://www.ryanchapin.com/fv-m/Ryan), original post found: [source](http://www.ryanchapin.com/fv-b-4-737/Getting-Markdown-Viewer-To-Display-HTML-Formatted-Markdown-Content-in-Firefox-Under-Linux.html)

**Comment by Thiht** [comment] 2015-11-23 16:11
I think I finally found the fix, now working on my Fedora 22/Firefox 42.0. :)

Can I have some feedback before I push the changes to addons.mozilla?

**Comment by Thiht** [comment] 2015-11-25 19:34
If you want to try the fix I published a pre-release here: https://github.com/Thiht/markdown-viewer/releases/tag/v1.9-pre
Note it won't work if electrolysis is enabled (Firefox 43+ I think), see #46.

**Comment by wangjiezhe** [comment] 2015-11-26 02:03
It now works fine for me on `firefox 42.0` on `Arch`

**Comment by Thiht** [comment] 2015-11-26 09:47
Cool, I'll update the AMO version later today :)

**Comment by Thiht** [comment] 2015-11-26 21:21
I just updated the new version to AMO, it should be updated in a few days if nothing goes wrong. I suggest you switch back to the signed version when it's updated to obtain possible future updates.

**Closed by Thiht** 2015-11-26 21:21 UTC

**Comment by davidegiannella** [comment] 2016-01-04 14:42
Sorry for very late reply. I can confirm that the 1.9 version fix the issue. Thanks @Thiht
