### ISSUE TITLE
Add elementary instructions!

### ISSUE THREAD

**Issue by tallforasmurf** [Thiht/markdown-viewer#41] opened 2015-06-06 18:16 UTC
I installed the add-on but cannot figure out how to use it. I have a .md file but if I do File>Open, Firefox asks what to do with this? "Open with Xcode (default)", DownThemAll!, Save File?

I cannot see how to get a Firefox window containing .md source, as shown in your screen shot. And if I do, how then do I say, "render this"?

**Comment by NicolasCARPi** [comment] 2015-06-12 22:28
:+1:

**Comment by regulatre** [comment] 2015-07-14 12:11
Same problem...

**Comment by Thiht** [comment] 2015-07-16 12:23
It's supposed to work out of the box the way you use it, something might be broken with the latest versions of Firefox... I'll try to look into it ASAP.

**Comment by NicolasCARPi** [comment] 2015-07-16 12:32
FYI, it doesn't work with Firefox 39.0.

**Comment by Thiht** [comment] 2015-11-23 16:09
Duplicate of #36

**Closed by Thiht** 2015-11-23 16:09 UTC
